server:
  port: 8082

#数据源配置
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/microservice
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    druid:
      max-wait: 6000
      initial-size: 10
      min-idle: 10
      max-active: 200

mybatis-plus:
  type-aliases-package: com.ataraxia.microservices.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  global-config:
    db-config:
      #主键自增
      id-type: auto

#SQL 日志
logging:
  level:
    com.ataraxia.microservices.dao: debug
    org.springframework.security.oauth2: debug

